[phases]
  install = { commands = ["npm install"] }
  build = { commands = ["npm run build"] }
  start = { commands = ["npm run start"] }

[variables]
  NEXT_PUBLIC_API_URL = "https://beshopping-bo.designtheflow.com"
  NODE_ENV = "production"
